export const emp = [
  {
    id: 1,
    fastname: "Alice",
    lastname: "Smith",
    email: "abc@gamil.com",
    phone: "1234567890",
    address: "123 Main St, Springfield, USA",
    age: 25,
    salary: 50000,
    department: "Engineering",
    position: "Software Engineer",
    imgurl: "https://example.com/images/alice.jpg",
  },
  {
    id: 2,
    fastname: "Jyoti",
    lastname: "Mourya",
    email: "abc@gamil.com",
    phone: "1234567890",
    address: "123 Main St, Springfield, USA",
    age: 25,
    salary: 50000,
    department: "Engineering",
    position: "Software Engineer",
    imgurl: "https://example.com/images/alice.jpg",
  },

  {
    id: 3,
    fastname: "Ajay",
    lastname: "Smith",
    email: "abc@gamil.com",
    phone: "1234567890",
    address: "123 Main St, Springfield, USA",
    age: 25,
    salary: 50000,
    department: "Engineering",
    position: "Software Engineer",
    imgurl: "https://example.com/images/alice.jpg",
  },
];
